ktor {
    deployment {
        port = 8080
        host = "0.0.0.0"
    }
}

app {
    db {
        host = "localhost"
        port = 1433
        name = "kidu_aventumundo"
        user = "kidu_api"
        password = "476235Isma"
        encrypt = true
        trustServerCertificate = true
    }
}
