@baseUrl = http://localhost:8080

### Login success
POST {{baseUrl}}/login
Content-Type: application/json

{
  "nickname": "kidu123",
  "password_hash": "1234"
}

### Login failed
POST {{baseUrl}}/login
Content-Type: application/json

{
  "nickname": "kidu123",
  "password_hash": "wrong"
}
