@baseUrl = http://localhost:8080

### Register user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "id": 0,
  "name": "Ismael",
  "age": 9,
  "nickname": "kidu123",
  "password_hash": "1234",
  "avatar_id": "avatar_1",
  "security_question": "Color favorito",
  "security_answer_hash": "azul",
  "stars": 0,
  "is_active": true
}

### Get user by nickname
GET {{baseUrl}}/users/kidu123
Accept: application/json
